declare @GUID varchar(255)
SET @GUID = NEWID()
 SELECT @GUID as 'A', 
 'PayerId' as 'B', 
 'PayerName' as 'C', 
 InsuranceCompanyAddresses.AddressName as 'D', 
 InsuranceCompanyAddresses.AddressName2 as 'E', 
 InsuranceCompanyAddresses.City as 'F', 
 InsuranceCompanyAddresses.State as 'G', 
 InsuranceCompanyAddresses.Zip as 'H',
 7 as 'I', 
 Patients.ClaimNumber as 'J', 
 Patients.LName as 'K', 
 Patients.FName as 'L',
 Patients.MI as 'M', 
 CONVERT(char(10), Patients.DOB,126) as 'N', 
 case when Patients.Sex='M' then 1 else 2 end as 'O',
 case Patients.CaseTypeID when 2 then 2 else 1 end as 'P',
 case Patients.CaseTypeID when 2 then Patients.EmployerName else Patients.PolicyHolderLName end as 'Q',
 case Patients.CaseTypeID when 2 then '' else Patients.PolicyHolderFName end as 'R',
 case Patients.CaseTypeID when 2 then '' else Patients.PolicyHolderMI end as 'S',
 Patients.Address1 as 'T', 
 Patients.City as 'U', 
 Patients.State as 'V', 
 Patients.Zip as 'W',
 replace(replace(replace(replace(Patients.Phone1,'(',''),')',''),'-',''),' ','') as 'X',
  case Patients.CaseTypeID when 2 then 4 else 1 end as 'Y',
  case Patients.CaseTypeID when  2 then EmployerAddress else case when PolicyHolderFName = Patients.fname and PolicyHolderLName = Patients.LName then Patients.Address1 else PolicyHolderAddress end end as 'Z',
  case Patients.CaseTypeID when  2 then EmployerAddress else case when PolicyHolderFName = Patients.fname and PolicyHolderLName = Patients.LName then Patients.City else PolicyHolderCity end end as 'AA',
  case Patients.CaseTypeID when  2 then EmployerAddress else case when PolicyHolderFName = Patients.fname and PolicyHolderLName = Patients.LName then Patients.State else PolicyHolderState end end as 'AB',
  case Patients.CaseTypeID when  2 then EmployerAddress else case when PolicyHolderFName = Patients.fname and PolicyHolderLName = Patients.LName then Patients.Zip else PolicyHolderZip end end as 'AC',
  '' as 'AE', 
  '' as 'AF', 
  '' as 'AG', 
  '' as 'AH', 
  '' as 'AI', 
  case Patients.CaseTypeID when  2  then 1 else 2 end as 'AJ',
  case Patients.CaseTypeID when 2  then 2 else 1 end as 'AK',
  '' as 'AL', 
  2 as 'AM', 
  '' as 'AN',
  '' as 'AO',
  case when PolicyHolderFName = Patients.fname and PolicyHolderLName = Patients.LName then CONVERT(char(10), Patients.DOB,126)  else 'UNK' end as 'AP',
  case when PolicyHolderFName = Patients.fname and PolicyHolderLName = Patients.LName then   case when Patients.Sex ='M' then 1 else 2 end else 3 end as 'AQ',
  Patients.ClaimNumber as 'AR',
  '' as 'AS',
  '' as 'AT',
  1 as 'AU',
  CONVERT(char(10), BillDate,126) as 'AV',
  '' as 'AW',
  CONVERT(char(10), DOA,126)  as 'AX',
  '' as 'AY',
  '' as 'AZ',
  '' as 'BA',
  '' as 'BB',
  '' as 'BC',
  '' as 'BD',
  '' as 'BE',
  '' as 'BF',
  '' as 'BG',
  '' as 'BH',
  '' as 'BI',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 0 rows FETCH NEXT 1 ROWS ONLY) as 'BJ',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 1 rows FETCH NEXT 1 ROWS ONLY) as 'BK',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 2 rows FETCH NEXT 1 ROWS ONLY) as 'BL',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 3 rows FETCH NEXT 1 ROWS ONLY) as 'BM',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 4 rows FETCH NEXT 1 ROWS ONLY) as 'BN',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 5 rows FETCH NEXT 1 ROWS ONLY) as 'BO',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 6 rows FETCH NEXT 1 ROWS ONLY) as 'BP',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 7 rows FETCH NEXT 1 ROWS ONLY) as 'BQ',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 8 rows FETCH NEXT 1 ROWS ONLY) as 'BR',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 9 rows FETCH NEXT 1 ROWS ONLY) as 'BS',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 10 rows FETCH NEXT 1 ROWS ONLY) as 'BT',
(select ICDCode from BillDiagnosis where BillDiagnosis.BillID=Bills.BillID order by PatientProcedureID OFFSET 11 rows FETCH NEXT 1 ROWS ONLY) as 'BU',
  '' as 'BV',
  '' as 'BW',
  '' as 'BX',
BP.CorporationTaxID as 'BY',
2 as 'BZ',
patients.PatientID as 'CA',
1 as 'CB',
Bills.BillAmount as 'CC',
0 as 'CD',
1 as 'CE',
rtrim(TR.Fname) + ' ' + rtrim(TR.Lname) as 'CF',
CONVERT(char(10), Bills.BillDate,126)  as 'CG',
Offices.OfficeName as 'CH',
Offices.Address1 as 'CI',
Offices.Address2 as 'CJ',
Offices.City as 'CK',
Offices.State as 'CL',
Offices.Zip as 'CM',
replace(replace(replace(replace(Offices.Phone1,'(',''),')',''),'-',''),' ','') as 'CN',
'' as 'CO',
'' as 'CP',
Offices.OfficeName as 'CQ',
Offices.Address1 as 'CR',
Offices.Address2 as 'CS',
Offices.City as 'CT',
Offices.State as 'CU',
Offices.Zip as 'CV',
replace(replace(replace(replace(Offices.Phone1,'(',''),')',''),'-',''),' ','') as 'CW',
bp.WCProviderNPI as 'CX',
'' as 'CY',
ROW_NUMBER() OVER(ORDER BY BillProcedures.PatientProcedureID) as 'CZ',
CONVERT(char(10), Schedule.ScheduleDateTime,126) as 'DA',
CONVERT(char(10), Schedule.ScheduleDateTime,126) as 'DB',
11 as 'DC',
'' as 'DD',
BillProcedures.Code as 'DE',
'' as 'DF',
'' as 'DG',
'' as 'DH',
'' as 'DI',
'' as 'DJ',
(select TOP 1 ICDCode from BillDiagnosis where BillDiagnosis.PatientProcedureID=BillProcedures.PatientProcedureID) as 'DK',
BillProcedures.WCCost as 'DL',
'' as 'DN',
'' as 'DO',
'' as 'DP',
'' as 'DQ',
'' as 'DR',
'' as 'DS',
10 as 'DT',
TR.WCProviderNPI as 'DU',
'' as 'DV',
'' as 'DW',
'' as 'DX',
rtrim(TR.Fname) + ' ' + rtrim(TR.Lname )as 'DY',
'' as 'DZ',
'' as 'EA',
'' as 'EB',
'' as 'EC',
'' as 'ED',
'' as 'EE',
'' as 'EF',
'' as 'EG',
'' as 'EH',
'' as 'EI',
'' as 'EJ',
'' as 'EK',
'' as 'EL',
'' as 'EM',
'' as 'EN',
'' as 'EO',
'' as 'EP',
'' as 'EQ'
 FROM   Bills INNER JOIN Patients Patients ON Bills.PatientID=Patients.PatientID 
 INNER JOIN InsuranceCompanyAddresses ON Bills.InsAddressID=InsuranceCompanyAddresses.AddressID
 inner join BillProcedures on bills.BillID = BillProcedures.BillID
 inner join Procedures on Procedures.ProcID = BillProcedures.ProcID
 inner join PatientProcedures on BillProcedures.PatientProcedureID = PatientProcedures.PatientProcedureID
 inner join Employees BP on PatientProcedures.BillingProviderID = BP.EmpID
 inner join Employees TR on PatientProcedures.TreatingProviderID = TR.EmpID
 inner join Offices on PatientProcedures.OfficeID = Offices.OfficeID
 inner join Schedule on Schedule.ScheduleID = PatientProcedures.ScheduleID
  WHERE  Bills.BillID=2
